version: '2'

services:
  standalone:
    image: proxyco/pulsar
    ports:
      - "8080:8080" # Pulsar REST API
      - "6650:6650" # Pulsar native protocol
      - "2181:2181" # Zookeeper
      - "1883:1883" # MQTT
      - "9092:9092" # Kafka
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
      - PULSAR_PREFIX_messagingProtocols=kafka,mqtt
      - PULSAR_PREFIX_protocolHandlerDirectory=/pulsar/protocols
      - PULSAR_PREFIX_allowAutoTopicCreationType=partitioned
      - PULSAR_PREFIX_kafkaListeners=PLAINTEXT://127.0.0.1:9092
      - PULSAR_PREFIX_mqttListeners=mqtt://127.0.0.1:1883
      - PULSAR_PREFIX_advertisedAddress=127.0.0.1
      - PULSAR_PREFIX_brokerEntryMetadataInterceptors=org.apache.pulsar.common.intercept.AppendIndexMetadataInterceptor
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone --advertised-address standalone"
  dashboard:
    image: apachepulsar/pulsar-dashboard
    depends_on:
      - standalone
    ports:
      - "80:9527"
    environment:
      - SERVICE_URL=http://standalone:8080
